const services=[['Sunday','9:00 AM','Sunday Worship'],['Wednesday','7:00 PM','Midweek Bible Study'],['Saturday','7:00 PM','Saturday Bible Study']];
const ministries=[['Prayer','A place to seek God together and build a life of prayer.'],['Bible Study','Growing in the Word through faithful teaching and discussion.'],['Youth','Helping the next generation know, love, and serve God.'],['Music','Using worship and music to glorify Jesus Christ.']];
export default function Home(){return <main>
<nav className="nav"><a className="brand" href="#home"><span className="brand-mark">NL</span><span>NEW LIFE<br/><small>APOSTOLIC CHURCH</small></span></a><div className="links"><a href="#about">About</a><a href="#services">Services</a><a href="#ministries">Ministries</a><a href="#sermons">Sermons</a><a href="#contact">Contact</a></div><a className="nav-button" href="#visit">Visit Us</a></nav>
<section id="home" className="hero"><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">ONE GOD • ONE FAITH • ONE LORD</p><h1>Hear, O Israel:<br/><em>The LORD our God is one LORD.</em></h1><p className="verse">“And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.” — Deuteronomy 6:4–5</p><div className="hero-actions"><a className="primary" href="#visit">Join Us This Sunday</a><a className="secondary" href="#sermons">Watch Sermons</a></div></div><div className="scroll">SCROLL TO DISCOVER <span>↓</span></div></section>
<section id="visit" className="welcome"><div><p className="eyebrow dark">YOU ARE WELCOME HERE</p><h2>A place to <span>know God,</span><br/>grow in faith, and serve.</h2></div><p className="welcome-copy">Whether you are visiting for the first time or looking for a church family, we invite you to worship with us. Come as you are and discover a community centered on Jesus Christ and His Word.</p></section>
<section id="services" className="section"><div className="section-heading"><p className="eyebrow dark">WORSHIP WITH US</p><h2>Service Schedule</h2><p>Set aside time to worship, learn, pray, and fellowship together.</p></div><div className="service-grid">{services.map(s=><article className="service-card" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><p>{s[2]}</p></article>)}</div></section>
<section id="about" className="about"><div className="about-art"><span>JESUS</span></div><div className="about-copy"><p className="eyebrow">OUR HEART</p><h2>Built on the <em>Word.</em><br/>Centered on <em>Christ.</em></h2><p>New Life Apostolic Church of Jesus Christ Inc. exists to proclaim the Gospel, make disciples, strengthen families, and help people encounter the transforming presence of God.</p><p>We believe the church is more than a building. It is a people called to live out the faith with love, holiness, prayer, and service.</p><a className="text-link" href="#ministries">Discover our ministries →</a></div></section>
<section id="ministries" className="section"><div className="section-heading"><p className="eyebrow dark">GET INVOLVED</p><h2>Find Your Place</h2></div><div className="ministry-grid">{ministries.map((m,i)=><article className="ministry-card" key={m[0]}><div className="number">0{i+1}</div><h3>{m[0]}</h3><p>{m[1]}</p></article>)}</div></section>
<section id="sermons" className="sermons"><div className="section-heading light"><p className="eyebrow">THE WORD OF GOD</p><h2>Latest Sermons</h2><p>Watch, listen, and continue growing wherever you are.</p></div><div className="sermon-feature"><div className="play">▶</div><div><p className="sermon-label">FEATURED MESSAGE</p><h3>The God Beyond the Horizon of Time</h3><p>“Redeeming the time, because the days are evil.” — Ephesians 5:16</p><a href="#" className="secondary">Watch on YouTube</a></div></div></section>
<section className="cta"><p className="eyebrow dark">COME AND SEE</p><h2>There is a place for you<br/><span>at New Life.</span></h2><a className="primary dark-button" href="#contact">Plan Your Visit</a></section>
<footer id="contact"><div className="footer-brand"><span className="brand-mark">NL</span><div><strong>NEW LIFE APOSTOLIC</strong><br/><small>CHURCH OF JESUS CHRIST INC.</small></div></div><div className="footer-columns"><div><h4>Visit</h4><p>Service location<br/>Add church address here<br/>Philippines</p></div><div><h4>Connect</h4><p>Facebook<br/>YouTube<br/>Contact Us</p></div><div><h4>Services</h4><p>Sunday Worship<br/>Bible Study<br/>Prayer Meeting</p></div></div><div className="copyright">© 2026 New Life Apostolic Church of Jesus Christ Inc. All rights reserved.</div></footer>
</main>}
